# Generated by Django 3.2 on 2022-04-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu_input_standard_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Kedatangan_Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_batch', models.CharField(max_length=225)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(max_length=225)),
                ('nama', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Menu_input_standard_product.standard_product')),
            ],
        ),
    ]
