# Generated by Django 3.2 on 2022-04-16 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Standard_Product',
            fields=[
                ('nama', models.CharField(max_length=255, primary_key=True, serialize=False)),
                ('standard_sc', models.CharField(max_length=225)),
                ('standard_ph', models.CharField(max_length=225)),
                ('standard_appearance', models.CharField(max_length=255)),
            ],
        ),
    ]
