# Generated by Django 3.2 on 2022-04-16 08:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Menu_kedatangan_product', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Record_Hasil_Pengecekan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomor_batch', models.CharField(max_length=225)),
                ('quantity', models.IntegerField()),
                ('supplier', models.CharField(max_length=225)),
                ('standard_sc', models.CharField(max_length=225)),
                ('standard_ph', models.CharField(max_length=225)),
                ('standard_appearance', models.CharField(max_length=255)),
                ('actual_sc', models.CharField(max_length=225)),
                ('actual_ph', models.CharField(max_length=225)),
                ('actual_appearance', models.CharField(max_length=255)),
                ('status', models.CharField(choices=[('ok', 'OK'), ('ng', 'NG')], max_length=225, null=True)),
                ('nama', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Menu_kedatangan_product.kedatangan_product')),
            ],
        ),
    ]
